package me.iticket.android.singleton;

import android.content.Context;
import me.iticket.android.dto.EventDTO;

/**
 * Created by Vinicius Arruda on 09/12/2016.
 */

public class DataHolder {
    private static DataHolder dataHolder = new DataHolder();
    private Context context;
    private EventDTO event;

    public static DataHolder getInstance()
    {
        return dataHolder;
    }

    public Context getContext() {
        return context;
    }

    public void setContext(Context context) {
        this.context = context;
    }

    public EventDTO getEvent() {
        return event;
    }

    public void setEvent(EventDTO event) {
        this.event = event;
    }
    
    public void initializeDB(){
        try{
            // Create a manager:
            Manager manager = null;
            manager = new Manager(new AndroidContext(getApplicationContext()), Manager.DEFAULT_OPTIONS);
            // Create or open the database named iticket:
            database = manager.getDatabase("iticket");
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public Object getFromDatabase(String property, Class type){
        try{
            if(database!=null){
                ObjectMapper mapper = new ObjectMapper();
                // Read document from database
                Document document = database.getDocument(property);
                Map<String, Object> map = document.getProperties();
                // Convert Map to POJO
                Object result = mapper.convertValue(map, type);
                return result;
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return null;
    }

    public boolean saveOnDatabase(String property, Object object){
        try{
            if(database!=null){
                ObjectMapper mapper = new ObjectMapper();
                // Convert POJO to Map
                Map<String, Object> map = mapper.convertValue(object, new TypeReference<Map<String, Object>>() {});
                // Create or open the document
                Document document = database.getDocument(property);
                // Save the document to the database
                try {
                    document.update(new Document.DocumentUpdater() {
                        @Override
                        public boolean update(UnsavedRevision newRevision) {
                            newRevision.setUserProperties(map);
                            return true;
                        }
                    });
                } catch (CouchbaseLiteException e) {
                    e.printStackTrace();
                }
                // Log the document ID (generated by the database)
                // and properties
                Log.d("iticket", String.format("Document ID :: %s", document.getId()));
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return false;
    }
}
